on: push

name: CI

env:
  CI_CARGO_MAKE_VERSION: 0.35.16

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.59.0", "stable"]
    steps:
      - uses: hecrj/setup-rust-action@967aec96c6a27a0ce15c1dac3aaba332d60565e2
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt,clippy
      - uses: actions/checkout@v1
      - name: Install cargo-make
        run: |
          curl -LO "https://github.com/sagiegurari/cargo-make/releases/download/${CI_CARGO_MAKE_VERSION}/cargo-make-v${CI_CARGO_MAKE_VERSION}-x86_64-unknown-linux-musl.zip"
          unzip "cargo-make-v${CI_CARGO_MAKE_VERSION}-x86_64-unknown-linux-musl.zip"
          cp "cargo-make-v${CI_CARGO_MAKE_VERSION}-x86_64-unknown-linux-musl/cargo-make" ~/.cargo/bin/
          rm -r "cargo-make-v${CI_CARGO_MAKE_VERSION}-x86_64-unknown-linux-musl.zip" "cargo-make-v${CI_CARGO_MAKE_VERSION}-x86_64-unknown-linux-musl"
          cargo make --version
      - name: "Format / Build / Test"
        run: cargo make ci
        env:
          RUST_BACKTRACE: full
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        rust: ["1.59.0", "stable"]
    steps:
      - uses: actions/checkout@v1
      - uses: hecrj/setup-rust-action@967aec96c6a27a0ce15c1dac3aaba332d60565e2
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt,clippy
      - uses: actions/checkout@v1
      - name: Install cargo-make
        run: |
          curl -LO "https://github.com/sagiegurari/cargo-make/releases/download/${CI_CARGO_MAKE_VERSION}/cargo-make-v${CI_CARGO_MAKE_VERSION}-x86_64-pc-windows-msvc.zip"
          unzip "cargo-make-v${CI_CARGO_MAKE_VERSION}-x86_64-pc-windows-msvc.zip"
          cp "cargo-make-v${CI_CARGO_MAKE_VERSION}-x86_64-pc-windows-msvc.zip/cargo-make.exe" ~/.cargo/bin/
          rm -r "cargo-make-v${CI_CARGO_MAKE_VERSION}-x86_64-pc-windows-msvc.zip" "cargo-make-v${CI_CARGO_MAKE_VERSION}-x86_64-pc-windows-msvc"
          cargo make --version
        shell: bash
      - name: "Format / Build / Test"
        run: cargo make ci
        env:
          RUST_BACKTRACE: full
