on: push

name: CI

env:
  CI_CARGO_MAKE_VERSION: 0.35.16

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: ["1.59.0", "stable"]
    steps:
      - uses: hecrj/setup-rust-action@967aec96c6a27a0ce15c1dac3aaba332d60565e2
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt,clippy
      - uses: actions/checkout@v1
      - name: Install cargo-make
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: sagiegurari/cargo-make
          tag: ${{ env.CI_CARGO_MAKE_VERSION }}
      # - name: Add cargo-make to $PATH
      #   run: |
      #     ${RUNNER_TOOL_CACHE}/sagiegurari/cargo-make/${CI_CARGO_MAKE_VERSION}/${RUNNER_OS}-${RUNNER_ARCH}/
      - run: env
      - run: tree /opt/hostedtoolcache/sagiegurari/cargo-make/0.35.16/linux-x64
      - name: "Format / Build / Test"
        run: cargo make ci
        env:
          RUST_BACKTRACE: full
  windows:
    name: Windows
    runs-on: windows-latest
    strategy:
      matrix:
        rust: ["1.59.0", "stable"]
    steps:
      - uses: actions/checkout@v1
      - uses: hecrj/setup-rust-action@967aec96c6a27a0ce15c1dac3aaba332d60565e2
        with:
          rust-version: ${{ matrix.rust }}
          components: rustfmt,clippy
      - uses: actions/checkout@v1
      - name: Install cargo-make
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: sagiegurari/cargo-make
          tag: ${{ env.CI_CARGO_MAKE_VERSION }}
      - name: "Format / Build / Test"
        run: cargo make ci
        env:
          RUST_BACKTRACE: full
